Repository stackabletech/zookeeper-operator, pull requests merged in 2021-05, with the labels that each got.

#95 Added the usual derives for ZookeeperReference. Required to use that …
  crd/src/util.rs
Labels: priority/high, type/enhancement

#99 Fix command to run ZooKeeper
  operator/src/lib.rs
Labels: priority/critical, size/XS, type/bug

#100 Remove release flag and introduce build caching
  .github/workflows/rust.yml
Labels: priority/low, size/XS, type/enhancement

#102 Added clean command to rust build.
  .github/workflows/rust.yml
Labels: type/enhancement

#112 Added method package_name() to ZooKeeperVersion for different package…
  crd/src/lib.rs
  operator/src/lib.rs
Labels: priority/high, size/S, type/enhancement

#96 Use label selectors instead of hardcoded nodenames
  Cargo.lock
  crd/Cargo.toml
  crd/src/bin/generate_crd.rs
  crd/src/lib.rs
  crd/src/util.rs
  crd/zookeepercluster.crd.yaml
  examples/simple-zookeepercluster.yaml
  operator/Cargo.toml
  operator/src/lib.rs
  server/Cargo.toml
  server/src/main.rs
Labels: size/M, type/enhancement

#109 Build caching & cleaning for clippy
  .github/workflows/rust.yml
Labels: priority/low, size/XS, type/enhancement

#118 Include node-name in generated pod names
  operator/src/lib.rs
Labels: priority/critical, size/XS, type/bug

#124 Bring project up to current Stackable best practices
  .github/dependabot.yml
  .github/workflows/build_artifacts.yml
  .github/workflows/daily_security.yml
  .github/workflows/rust.yml
  Cargo.lock
  LICENSE
  README.adoc
  crd/Cargo.toml
  crd/src/lib.rs
  crd/src/util.rs
  deploy/crd/zookeepercluster.crd.yaml
  docs/modules/ROOT/pages/building.adoc
  operator/Cargo.toml
  operator/src/error.rs
  operator/src/lib.rs
  server/Cargo.toml
  server/packaging/rpm/SPECS/stackable-zookeeper-operator-server.spec
  server/src/main.rs
Labels: priority/low, type/enhancement
