Repository stackabletech/zookeeper-operator, pull requests merged in 2021-09, with the labels that each got.

#177 Project updates
  .github/dependabot.yml
  .github/workflows/rust.yml
  CHANGELOG.md
  Cargo.lock
  crd/Cargo.toml
  deny.toml
  operator/Cargo.toml
  server/Cargo.toml
Labels: type/enhancement, priority/low

#210 Use versioning crate from operator-rs
  CHANGELOG.md
  Cargo.lock
  deploy/crd/zookeepercluster.crd.yaml
  rust/crd/Cargo.toml
  rust/crd/src/lib.rs
  rust/operator-binary/Cargo.toml
  rust/operator/Cargo.toml
  rust/operator/src/lib.rs
Labels: type/enhancement, priority/high

#209 Adapt to sticky scheduler
  CHANGELOG.md
  Cargo.lock
  deploy/crd/zookeepercluster.crd.yaml
  docs/modules/ROOT/pages/building.adoc
  docs/modules/ROOT/pages/usage.adoc
  rust/crd/Cargo.toml
  rust/crd/src/lib.rs
  rust/operator-binary/Cargo.toml
  rust/operator/Cargo.toml
  rust/operator/src/error.rs
  rust/operator/src/lib.rs
Labels: type/enhancement, priority/high

#214 Changed to kube-rs 0.60 and k8s-openapi features v1.22.
  CHANGELOG.md
  Cargo.lock
  deploy/crd/zookeepercluster.crd.yaml
  rust/crd/Cargo.toml
  rust/crd/src/lib.rs
  rust/crd/src/util.rs
  rust/operator-binary/Cargo.toml
  rust/operator-binary/src/stackable-zookeeper-operator.rs
  rust/operator/Cargo.toml
  rust/operator/src/lib.rs
Labels: priority/high, type/dependencies

#223 Initial implementation of operator-rs command handling
  CHANGELOG.md
  Cargo.lock
  deploy/crd/restart.crd.yaml
  deploy/crd/start.crd.yaml
  deploy/crd/stop.crd.yaml
  deploy/crd/zookeepercluster.crd.yaml
  examples/restart.command.example.yaml
  examples/simple-zookeepercluster.yaml
  examples/start.command.example.yaml
  examples/stop.command.example.yaml
  rust/crd/Cargo.toml
  rust/crd/src/commands.rs
  rust/crd/src/lib.rs
  rust/operator-binary/build.rs
  rust/operator-binary/src/stackable-zookeeper-operator.rs
  rust/operator/src/lib.rs
Labels: type/enhancement, priority/high
