Repository stackabletech/zookeeper-operator, pull requests merged in 2021-07, with the labels that each got.

#145 Add cargo deny to CI
  .github/workflows/rust.yml
  Cargo.lock
  crd/Cargo.toml
  deny.toml
  operator/Cargo.toml
  server/Cargo.toml
Labels: priority/high, type/enhancement

#71 Allow changing configuration options
  Cargo.lock
  config.yaml
  crd/Cargo.toml
  crd/src/bin/generate_crd.rs
  crd/src/lib.rs
  crd/src/util.rs
  deploy/crd/zookeepercluster.crd.yaml
  examples/simple-zookeepercluster.yaml
  operator/Cargo.toml
  operator/src/error.rs
  operator/src/lib.rs
  server/Cargo.toml
  server/src/main.rs
Labels: type/enhancement

#146 Enable monitoring
  .gitignore
  Cargo.lock
  crd/src/lib.rs
  deploy/config-spec/properties.yaml
  deploy/crd/zookeepercluster.crd.yaml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/commandline_args.adoc
  docs/modules/ROOT/pages/configuration.adoc
  docs/modules/ROOT/pages/usage.adoc
  examples/simple-zookeepercluster.yaml
  operator/src/lib.rs
  server/Cargo.toml
  server/packaging/buildrpm.sh
  server/packaging/copy_assets.py
  server/packaging/rpm/SOURCES/stackable-zookeeper-operator-server-VERSION/usr/lib/systemd/system/stackable-zookeeper-operator-server.service
  server/packaging/rpm/SPECS/stackable-zookeeper-operator-server.spec
  server/src/main.rs
Labels: priority/high, type/enhancement

#156 Adapted optional replica changes and introduced admin port
  Cargo.lock
  crd/src/lib.rs
  deploy/config-spec/properties.yaml
  deploy/crd/zookeepercluster.crd.yaml
  examples/simple-zookeepercluster.yaml
  operator/src/lib.rs
Labels: priority/medium, type/enhancement
